version: '2'
services:
  db:
    image: mdillon/postgis
    container_name: db
  web:
    image: jtr1/ked-recruiter-api
    command: rails s -p 3000 -e production
    container_name: recruiter-web
    env_file: ./config/production.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  client:
    image: jtr1/ked-recruiter-client
    command: npm start
    container_name: recruiter-client
    ports:
      - "80:3000"
    depends_on:
      - web