version: '2'
services:
  db:
    image: mdillon/postgis
    container_name: db
    restart: always
  web:
    image: jtr1/ked-recruiter-app
    command: rails s -b 0.0.0.0 -p 3000 -e production
    container_name: recruiter-web
    env_file: ./config/environments/production.env
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=production
    depends_on:
      - db
    ports:
      - "80:3000"
    restart: always
