version: '2'
services:
  db:
    image: mdillon/postgis
    container_name: db
  web:
    image: jtr1/ked-recruiter-app
    command: foreman start
    container_name: recruiter-web
    env_file: ./config/environments/development.env
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "4000:4000"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - ./client:/app/client
