version: '2'
services:
  db:
    image: mdillon/postgis
    container_name: db
  web:
    image: jtr1/ked-recruiter-api
    command: rails s -p 3000 -e production
    container_name: recruiter-web
    ports:
      - "80:3000"
    depends_on:
      - db